### ISSUE TITLE
Quick feedback: limitations and formating issues

### ISSUE THREAD

**Issue by arthurjosse** [wormi4ok/evernote2md#10]
I have tried evernote2md (v0.9.0) for the first time – and probably the last since all my Evernote notes are now converted to Markdown. Here's how it went down:

- first attempts to convert a single enex file containing all my notes failed (executing evernote2md on that file simply did nothing, shell window closing after a few seconds without any error);
- then it worked with an enex file containing only half of my notes, but a couple of notes were missing;
- the missing notes had either their bodies (and/or titles, I don't remember) starting with an *, an highlight or a checkbox, or had the same title but different case (e.g. one was named "untitled", the other "Untitled" → in that case only one of the two notes was converted);
- after editing these notes so they don't start with any of those elements or don't have the same title, I have successfully convert all my notes from a single enex file.

The newly converted notes, now in plain markdown, have a few formating issues:

- Evernote highlights aren't converted in a Markdown equivalent (like mentionned in #6)
- A line break have been inserted between each item of bulleted and numbered lists (there shouldn't be any line break)
- Evernote tables are converted to illegible mixes of line breaks and pipes ( | )

Appart from all that, it works :ok_hand:

**Comment by wormi4ok** [comment]
Hello @arthurjosse ! Thanks a lot for comprehensive feedback!

The problem with lists and tables is something I will try to look into soon. Not sure if tables is an easy thing to do in markdown, but worth a shot.

I'm also curious why it failed to process a single enex file. What was the size/number of notes in the export?

Regarding highlights, there is no equivalent in markdown to convert text highlighted in Evernote, unfortunately. The closest one I see is _italic_, which is semantically to use since Evernote also allows to format text as italic. If you have any suggestions on how highlighted text should look in markdown - I'd be happy to discuss.

Thanks again!

**Comment by wormi4ok** [comment]
Hey @arthurjosse. 

I'm happy to let you know that the latest version [v0.10.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.10.0) fixes all three issues that you mentioned. 🎉

If you have a moment, please check it out and post here if the result was better this time.
