### ISSUE TITLE
To-do lists can't be conveted properly

### ISSUE THREAD

**Issue by weijianzz** [wormi4ok/evernote2md#50]
Hi Stanislav, i found that To-do lists can't be conveted properly. 

**Context**
below is to-do lists in my evernote notes.
![image](https://user-images.githubusercontent.com/18544010/124565091-40d1dc80-de74-11eb-8b0e-f1faba87d245.png)
Here is the convted result in markdown files.
![image](https://user-images.githubusercontent.com/18544010/124565336-82628780-de74-11eb-83fd-fcb72df7c345.png)

**Solution**
The proper result maybe be this pic.
![image](https://user-images.githubusercontent.com/18544010/124566178-66abb100-de75-11eb-9806-deb708b09d76.png)

**Comment by wormi4ok** [comment]
Hey! Thanks for the request. 

That's expected since Evernote uses a custom  `<en-todo>` tag to render to-do list items. I already have a [similar conversion rule](https://github.com/wormi4ok/evernote2md/blob/master/encoding/markdown/markdown.go#L52-L74) implemented, not sure yet if it's going to work well with list tags around. 

Rendering `*` in front of the checkbox could cause issues in some Markdown editors, I guess. For me, a clean to-do list in markdown should look like this, but it's gonna be tricky to remove `*` symbols already rendered before.

```
[x] First
[x] Second
[ ] Apple
[ ] Banana
```

Maybe someone can validate my assumptions?

**Comment by weijianzzz** [comment]
Hey! 

This format looks concise, but maybe cannot be recognized by mainstrean markdown software. Could the `-` or `+` symbols solve the issues caused by the rendering `*` in front of the checkboxs ?
