### ISSUE TITLE
Convert to Markdown but many image disappear

### ISSUE THREAD

**Issue by fekfoq259** [wormi4ok/evernote2md#7]
[here is demo](https://www.dropbox.com/sh/o6v7o26zn1z8bxe/AAAFS6iylb2VPPwdTVl3rUBza?dl=0)

**Comment by wormi4ok** [comment]
Hi @fekfoq259 !

Thanks for reporting the problem. This is an interesting edge case, image URLs in the note actually have the "name" attribute. I will try to find a good workaround tomorrow and create a new release soon.

It's very nice that you uploaded an example - this saved me a lot of time 👍

**Comment by wormi4ok** [comment]
Hello @fekfoq259 .

Could you please test this version https://github.com/wormi4ok/evernote2md/releases/tag/v0.6.0 and check if it works as expected?

**Comment by fekfoq259** [comment]
Yes. The problem has been solved. Thank you.

I also test orther page found orther issue.

- some long picture won't works will
- if notes have same title notes only remain one note

[update more demo](https://www.dropbox.com/sh/o6v7o26zn1z8bxe/AAAFS6iylb2VPPwdTVl3rUBza?dl=0)

**Comment by wormi4ok** [comment]
Hello again, @fekfoq259.

It turned out that the problem with the pictures you mentioned had nothing to do with the size, but with the original HTML source. 
The websites, you scrape pages from, contain valid, yet insufficient HTML-markup, and after converting them to Evernote notes, we get a poorly formatted export file. In general, for notes that you create yourself, you will get a much better result.

I'm trying to make `evernote2md` work with any kind of input and produce a valid result, but I'd recommend looking for some other tools to save the content of the websites. It appears that you still have access to most of them, and the result will be much better if you use the right tool.

Thanks again for the contribution, please give [v0.8.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.8.0) a try and let me know if it works for you!

**Comment by fekfoq259** [comment]
Problem has been solved in v0.8.0. Thank you again.
But I found another issue.
I use html clipper by OneNote than import to Evernote than export enex or html. In this process html's image will have same name.
Maybe we shouln't put all image in same folder.
[demo in here](https://www.dropbox.com/sh/o6v7o26zn1z8bxe/AAAFS6iylb2VPPwdTVl3rUBza?dl=0)

**Comment by wormi4ok** [comment]
Hello,
Yes, I'm aware of this issue and still thinking about the right way to implement a fix for it. I'd really like to keep this flat file structure, but in this case, there is no guarantee that filenames are unique in every note.

Meanwhile, you can try to isolate exports by running `evernote2md` for each export file individually:
```bash
for FILE in ./demo6-image-have-same-name/*.enex; do
  ./evernote2md $FILE ${FILE%.enex}
done
```

This should work in any OS that runs `bash`, e.g. Linux, macOS and WSL in Windows.

**Comment by fekfoq259** [comment]
Ok. Maybe we should use title and size add hash postfix. (If have same image name)
But I think export single enex is not a good idea.
